### ISSUE TITLE
Run eval-3dvnet.py got error

### ISSUE THREAD

**Issue by bityigoss** [alexrich021/3dvnet#4]
Hi, thanks for your excellent work.
After I installed the dependencies and prepared one scene(just for a quick running, e.g. scene0806_00) in ScanNet as followed with data_preprocess/preprocess_scannet.py. I run eval-3dvnet.py got error:

python eval-3dvnet.py

INFO - 2022-01-06 14:15:13,134 - acceleratesupport - No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
Loading model...
Preparing dataset...
1 / 1: scene0806_00
Making initial depth predictions
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  5.19it/s]
Refining depth pts
Iter 1 / 2
Traceback (most recent call last):
  File "eval-3dvnet.py", line 138, in <module>
    main('3dvnet', process_scene, dset_kwargs, net, depth=True)
  File "/root/3drec/3dvnet/mv3d/eval/main.py", line 59, in main
    depth_preds, init_prob, final_prob = pred_func(batch, scene, dset, net)
  File "eval-3dvnet.py", line 75, in process_scene
    xs, pts = net.model_scene(all_depth, depth_batch, all_feats_quarter, rotmats, tvecs, K, ref_src_edges,
  File "/root/3drec/3dvnet/mv3d/lightningmodel.py", line 174, in model_scene
    anchor_pts, anchor_idx3d, anchor_batch, anchor_pts_edges = utils.voxelize(pts, pts_batch, self.edge_len)
  File "/root/3drec/3dvnet/mv3d/utils.py", line 45, in voxelize
    voxel_idx = voxel_grid(pts, pts_batch, edge_len, bbox_min, bbox_max)
  File "/root/miniconda3/envs/3dvnet/lib/python3.8/site-packages/torch_geometric/nn/pool/voxel_grid.py", line 58, in voxel_grid
    pos = torch.cat([pos, batch.unsqueeze(-1).type_as(pos)], dim=-1)
AttributeError: 'float' object has no attribute 'unsqueeze'

Can you help me?

**Comment by bityigoss** [comment]
Caused by different version of pytorch-geometric.
